### ISSUE TITLE
new repository checklist

### ISSUE THREAD

**Issue by rofe** [rofe/helix-service-test#1]
---
name: New Repository
about: Checklist for the creation of a new repository
title: ''
assignees: ''

---

Create a new repository with the name `helix-service-test`

- [x] Use [`helix-library`](https://github.com/adobe/helix-library) or [`helix-service`](https://github.com/adobe/helix-service) template
- [x] Set the repository description
- [x] Update the repository `README.md` (search for `adobe/helix-service` or `adobe/helix-library`)
- [x] Update the `statuspage` and `newrelic` config in `package.json`: decide if your service falls under Development, Publishing or Delivery. See https://status.project-helix.io for reference.
- [x] Set up [CircleCI](https://circleci.com/add-projects/gh/adobe)
